export type ServiceCategory =
  | "compute"
  | "storage"
  | "database"
  | "networking"
  | "integration"
  | "analytics"
  | "ml-ai"
  | "security"
  | "observability"
  | "devops";

export type AwsService = {
  code: string;
  name: string;
  category: ServiceCategory;
  oneLiner: string;
  whenToUse: string;
  pricingNote: string;
  docsUrl: string;
};

export const AWS_SERVICES: AwsService[] = [
  {
    code: "ec2",
    name: "Amazon EC2",
    category: "compute",
    oneLiner: "Resizable virtual machines.",
    whenToUse: "Long-running stateful workloads, full OS control, custom AMIs.",
    pricingNote: "Per-second billing; commit via Savings Plans / RIs for steady workloads.",
    docsUrl: "https://docs.aws.amazon.com/ec2/",
  },
  {
    code: "lambda",
    name: "AWS Lambda",
    category: "compute",
    oneLiner: "Event-driven serverless functions.",
    whenToUse: "Bursty workloads, glue logic, API backends with low concurrency.",
    pricingNote: "Per request + GB-seconds; idle is free.",
    docsUrl: "https://docs.aws.amazon.com/lambda/",
  },
  {
    code: "ecs",
    name: "Amazon ECS",
    category: "compute",
    oneLiner: "Container orchestration on AWS.",
    whenToUse: "Containerized services, prefer when you do not need full Kubernetes.",
    pricingNote: "Pay for underlying EC2 / Fargate.",
    docsUrl: "https://docs.aws.amazon.com/ecs/",
  },
  {
    code: "fargate",
    name: "AWS Fargate",
    category: "compute",
    oneLiner: "Serverless containers for ECS / EKS.",
    whenToUse: "Containers without managing servers; pay per task.",
    pricingNote: "Per vCPU-second + GB-second.",
    docsUrl: "https://docs.aws.amazon.com/fargate/",
  },
  {
    code: "eks",
    name: "Amazon EKS",
    category: "compute",
    oneLiner: "Managed Kubernetes.",
    whenToUse: "Existing Kubernetes investment or multi-cloud portability.",
    pricingNote: "$0.10/hr per cluster + node costs.",
    docsUrl: "https://docs.aws.amazon.com/eks/",
  },
  {
    code: "s3",
    name: "Amazon S3",
    category: "storage",
    oneLiner: "Object storage with eleven nines durability.",
    whenToUse: "Static assets, data lake, backups, logs.",
    pricingNote: "Per GB-month + requests; cheaper tiers for cold data.",
    docsUrl: "https://docs.aws.amazon.com/s3/",
  },
  {
    code: "ebs",
    name: "Amazon EBS",
    category: "storage",
    oneLiner: "Block storage volumes for EC2.",
    whenToUse: "Persistent volumes for EC2 instances; databases on EC2.",
    pricingNote: "Per GB-month + IOPS for provisioned tiers.",
    docsUrl: "https://docs.aws.amazon.com/ebs/",
  },
  {
    code: "efs",
    name: "Amazon EFS",
    category: "storage",
    oneLiner: "Managed NFS file system.",
    whenToUse: "Shared POSIX filesystem across containers / instances.",
    pricingNote: "Per GB-month; cheaper IA tier available.",
    docsUrl: "https://docs.aws.amazon.com/efs/",
  },
  {
    code: "rds",
    name: "Amazon RDS",
    category: "database",
    oneLiner: "Managed relational databases.",
    whenToUse: "Postgres, MySQL, MariaDB, Oracle, SQL Server with managed backups.",
    pricingNote: "Instance + storage + IOPS; reserved instances available.",
    docsUrl: "https://docs.aws.amazon.com/rds/",
  },
  {
    code: "aurora",
    name: "Amazon Aurora",
    category: "database",
    oneLiner: "MySQL/Postgres-compatible cloud-native database.",
    whenToUse: "Higher throughput and HA than RDS; serverless v2 for variable load.",
    pricingNote: "ACU-hour for serverless; instance + storage for provisioned.",
    docsUrl: "https://docs.aws.amazon.com/aurora/",
  },
  {
    code: "dynamodb",
    name: "Amazon DynamoDB",
    category: "database",
    oneLiner: "Managed key-value / document store.",
    whenToUse: "Predictable single-digit-ms latency; large scale; serverless.",
    pricingNote: "Pay per request or provisioned RCU/WCU.",
    docsUrl: "https://docs.aws.amazon.com/dynamodb/",
  },
  {
    code: "elasticache",
    name: "Amazon ElastiCache",
    category: "database",
    oneLiner: "Managed Redis or Memcached.",
    whenToUse: "Caching, session store, leaderboards, pub/sub.",
    pricingNote: "Per node-hour.",
    docsUrl: "https://docs.aws.amazon.com/elasticache/",
  },
  {
    code: "vpc",
    name: "Amazon VPC",
    category: "networking",
    oneLiner: "Virtual private cloud.",
    whenToUse: "Network isolation, subnets, route tables, security groups.",
    pricingNote: "VPC itself is free; NAT Gateway and endpoints have per-GB cost.",
    docsUrl: "https://docs.aws.amazon.com/vpc/",
  },
  {
    code: "alb",
    name: "Application Load Balancer",
    category: "networking",
    oneLiner: "Layer 7 HTTP/HTTPS load balancer.",
    whenToUse: "Routing by path/host, microservices, WebSockets.",
    pricingNote: "Per LCU-hour.",
    docsUrl: "https://docs.aws.amazon.com/elasticloadbalancing/",
  },
  {
    code: "cloudfront",
    name: "Amazon CloudFront",
    category: "networking",
    oneLiner: "Global CDN.",
    whenToUse: "Static assets, edge caching, DDoS shielding, signed URLs.",
    pricingNote: "Per GB out + per 10k requests; free egress to S3 origin.",
    docsUrl: "https://docs.aws.amazon.com/cloudfront/",
  },
  {
    code: "route53",
    name: "Amazon Route 53",
    category: "networking",
    oneLiner: "Authoritative DNS + health checks.",
    whenToUse: "DNS hosting, latency-based routing, failover.",
    pricingNote: "Per hosted zone + per query.",
    docsUrl: "https://docs.aws.amazon.com/route53/",
  },
  {
    code: "apigw",
    name: "Amazon API Gateway",
    category: "integration",
    oneLiner: "Managed API frontend (REST/HTTP/WebSocket).",
    whenToUse: "Expose Lambda or container backends as APIs.",
    pricingNote: "Per request; HTTP API is cheaper than REST API.",
    docsUrl: "https://docs.aws.amazon.com/apigateway/",
  },
  {
    code: "sqs",
    name: "Amazon SQS",
    category: "integration",
    oneLiner: "Managed message queue.",
    whenToUse: "Decouple producers and consumers; buffer load spikes.",
    pricingNote: "$0.40 per million requests.",
    docsUrl: "https://docs.aws.amazon.com/sqs/",
  },
  {
    code: "sns",
    name: "Amazon SNS",
    category: "integration",
    oneLiner: "Pub/sub messaging.",
    whenToUse: "Fan-out to multiple subscribers; SMS/email/HTTP notifications.",
    pricingNote: "Per million publishes / deliveries.",
    docsUrl: "https://docs.aws.amazon.com/sns/",
  },
  {
    code: "eventbridge",
    name: "Amazon EventBridge",
    category: "integration",
    oneLiner: "Serverless event bus.",
    whenToUse: "Event-driven architectures, SaaS event ingestion, schema registry.",
    pricingNote: "Per million events.",
    docsUrl: "https://docs.aws.amazon.com/eventbridge/",
  },
  {
    code: "stepfunctions",
    name: "AWS Step Functions",
    category: "integration",
    oneLiner: "Serverless workflow orchestration.",
    whenToUse: "Long-running workflows, sagas, retry logic, parallel branches.",
    pricingNote: "Per state transition (Standard) or per workflow (Express).",
    docsUrl: "https://docs.aws.amazon.com/step-functions/",
  },
  {
    code: "msk",
    name: "Amazon MSK",
    category: "integration",
    oneLiner: "Managed Apache Kafka.",
    whenToUse: "High-throughput streaming, replay, ordered partitions.",
    pricingNote: "Per broker-hour + storage.",
    docsUrl: "https://docs.aws.amazon.com/msk/",
  },
  {
    code: "kinesis",
    name: "Amazon Kinesis Data Streams",
    category: "analytics",
    oneLiner: "Managed real-time streaming.",
    whenToUse: "Telemetry ingestion, clickstream, log streaming.",
    pricingNote: "Per shard-hour + per GB ingested (on-demand).",
    docsUrl: "https://docs.aws.amazon.com/kinesis/",
  },
  {
    code: "glue",
    name: "AWS Glue",
    category: "analytics",
    oneLiner: "Serverless ETL + data catalog.",
    whenToUse: "Spark ETL on data lake; cataloging S3.",
    pricingNote: "Per DPU-hour.",
    docsUrl: "https://docs.aws.amazon.com/glue/",
  },
  {
    code: "athena",
    name: "Amazon Athena",
    category: "analytics",
    oneLiner: "Serverless SQL on S3.",
    whenToUse: "Ad-hoc analytics, log queries, data lake exploration.",
    pricingNote: "$5 per TB scanned (Parquet + partitions reduce cost).",
    docsUrl: "https://docs.aws.amazon.com/athena/",
  },
  {
    code: "redshift",
    name: "Amazon Redshift",
    category: "analytics",
    oneLiner: "Managed data warehouse.",
    whenToUse: "BI workloads, large-scale analytics, complex joins.",
    pricingNote: "Per node-hour or per RPU-hour (serverless).",
    docsUrl: "https://docs.aws.amazon.com/redshift/",
  },
  {
    code: "bedrock",
    name: "Amazon Bedrock",
    category: "ml-ai",
    oneLiner: "Foundation models as API.",
    whenToUse: "GenAI features without managing model infra.",
    pricingNote: "Per input/output token; provisioned throughput available.",
    docsUrl: "https://docs.aws.amazon.com/bedrock/",
  },
  {
    code: "sagemaker",
    name: "Amazon SageMaker",
    category: "ml-ai",
    oneLiner: "Managed ML platform.",
    whenToUse: "Training, tuning and hosting custom ML models.",
    pricingNote: "Per instance-hour for training and endpoints.",
    docsUrl: "https://docs.aws.amazon.com/sagemaker/",
  },
  {
    code: "iam",
    name: "AWS IAM",
    category: "security",
    oneLiner: "Identity and access management.",
    whenToUse: "Roles, policies, federation, fine-grained permissions.",
    pricingNote: "Free.",
    docsUrl: "https://docs.aws.amazon.com/iam/",
  },
  {
    code: "kms",
    name: "AWS KMS",
    category: "security",
    oneLiner: "Managed encryption keys.",
    whenToUse: "Envelope encryption for S3/EBS/RDS, signing, KMS-backed CMK rotation.",
    pricingNote: "$1/CMK-month + per request.",
    docsUrl: "https://docs.aws.amazon.com/kms/",
  },
  {
    code: "secretsmanager",
    name: "AWS Secrets Manager",
    category: "security",
    oneLiner: "Managed secret rotation.",
    whenToUse: "Database credentials, API keys, with automatic rotation.",
    pricingNote: "$0.40/secret-month + per 10k API calls.",
    docsUrl: "https://docs.aws.amazon.com/secretsmanager/",
  },
  {
    code: "waf",
    name: "AWS WAF",
    category: "security",
    oneLiner: "Web application firewall.",
    whenToUse: "Protect ALB / CloudFront / API Gateway from common exploits.",
    pricingNote: "Per Web ACL + per million requests + per rule.",
    docsUrl: "https://docs.aws.amazon.com/waf/",
  },
  {
    code: "cloudwatch",
    name: "Amazon CloudWatch",
    category: "observability",
    oneLiner: "Metrics, logs, alarms, dashboards.",
    whenToUse: "Default observability layer for AWS workloads.",
    pricingNote: "Per metric + per GB ingested for logs.",
    docsUrl: "https://docs.aws.amazon.com/cloudwatch/",
  },
  {
    code: "xray",
    name: "AWS X-Ray",
    category: "observability",
    oneLiner: "Distributed tracing.",
    whenToUse: "Trace requests across Lambda, ECS, API Gateway, etc.",
    pricingNote: "Per million traces.",
    docsUrl: "https://docs.aws.amazon.com/xray/",
  },
  {
    code: "codebuild",
    name: "AWS CodeBuild",
    category: "devops",
    oneLiner: "Managed CI build runner.",
    whenToUse: "Build and test pipelines integrated with CodePipeline.",
    pricingNote: "Per build minute by compute size.",
    docsUrl: "https://docs.aws.amazon.com/codebuild/",
  },
  {
    code: "codepipeline",
    name: "AWS CodePipeline",
    category: "devops",
    oneLiner: "Managed CI/CD orchestration.",
    whenToUse: "End-to-end delivery pipelines on AWS.",
    pricingNote: "$1 per active pipeline-month.",
    docsUrl: "https://docs.aws.amazon.com/codepipeline/",
  },
  {
    code: "cdk",
    name: "AWS CDK",
    category: "devops",
    oneLiner: "Infrastructure as code in TypeScript / Python / Java.",
    whenToUse: "Programmable IaC with constructs and unit tests.",
    pricingNote: "Free; pay for resources synthesized.",
    docsUrl: "https://docs.aws.amazon.com/cdk/",
  },
];

export const CATEGORY_LABELS: Record<ServiceCategory, string> = {
  compute: "Compute",
  storage: "Storage",
  database: "Database",
  networking: "Networking",
  integration: "Integration",
  analytics: "Analytics",
  "ml-ai": "ML / AI",
  security: "Security",
  observability: "Observability",
  devops: "DevOps",
};

export function servicesByCategory(category: ServiceCategory): AwsService[] {
  return AWS_SERVICES.filter((s) => s.category === category);
}

export function findService(code: string): AwsService | undefined {
  return AWS_SERVICES.find((s) => s.code === code);
}
